#ifndef RECENTPROJECTSDLL_GLOBAL_H
#define RECENTPROJECTSDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RECENTPROJECTSDLL_LIBRARY)
#  define RECENTPROJECTSDLL_EXPORT Q_DECL_EXPORT
#else
#  define RECENTPROJECTSDLL_EXPORT Q_DECL_IMPORT
#endif

#endif // RECENTPROJECTSDLL_GLOBAL_H
